name: Bump
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * * # At 08:00 every day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    name: Bump rendered version if changed
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run bump script
        run: |
          uv run tools/sync.py
          git status
          git diff

      - name: Get current version
        shell: python
        id: getver
        run: |
          import tomllib
          import os

          with open("pyproject.toml", "rb") as f:
              pyproject = tomllib.load(f)
          with open(os.environ["GITHUB_OUTPUT"], "w", encoding="utf-8") as f:
              print(f"version={pyproject['project']['version']}", file=f)

      - uses: peter-evans/create-pull-request@v8
        id: create-pr
        with:
          title: |
            chore(deps): bump version to ${{ steps.getver.outputs.version }}
          commit-message: |
            chore(deps): bump version to ${{ steps.getver.outputs.version }}
          body: |
            Update the stored schema files and bump to version ${{ steps.getver.outputs.version }}.

            PR generated by the "Update dependencies" [workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).

          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true

      - name: Enable pull request auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run:
          gh pr merge --squash --auto --delete-branch ${{
          steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.token }}
